import csv
import time
from typing import List, Tuple, Dict, Any


class CSVExporter:
    """Pure CSV export service for observation data"""
    
    def export_observations(self, responses: List[Tuple], filepath: str, metadata: Dict[str, Any]) -> bool:
        """Export observations to CSV file with metadata"""
        try:
            with open(filepath, "w", newline="", encoding='utf-8') as f:
                writer = csv.writer(f)
                
                # Add metadata as comment lines
                for key, value in metadata.items():
                    writer.writerow([f"# {key}: {value}"])
                
                # Add empty line separator
                writer.writerow([])
                
                # Data header and rows
                writer.writerow(["time_s", "category", "response", "value"])
                writer.writerows(responses)
            
            return True
            
        except Exception as e:
            print(f"Failed to export CSV: {e}")
            return False
    
    def create_metadata(self, config: Dict[str, Any], start_time: float, duration: float) -> Dict[str, str]:
        """Create metadata dictionary for CSV export"""
        protocol_name = config.get('name', 'Unknown')
        start_datetime = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(start_time))
        
        return {
            f"Protocol: {protocol_name}": "",
            f"Observation Started: {start_datetime}": "",
            f"Total Duration: {duration:.1f} seconds": "",
            "Generated by: REFLECT v1.0": ""
        }
